# Generated by Django 6.0.2 on 2026-02-13 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_message_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('credit_rating', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20, null=True)),
                ('background_check', models.CharField(blank=True, choices=[('clear', 'Clear'), ('flagged', 'Flagged'), ('review_needed', 'Review Needed')], max_length=20, null=True)),
                ('eviction_history', models.CharField(blank=True, choices=[('none_found', 'None Found'), ('records_found', 'Records Found')], max_length=20, null=True)),
                ('income_verified', models.BooleanField(null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('approved', 'Approved'), ('conditional', 'Conditional'), ('denied', 'Denied')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('report_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='properties.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
