# Generated by Django 6.0.2 on 2026-02-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_userprofile_is_org_admin_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='tenant',
            unique_together={('organization', 'email')},
        ),
    ]
