# Generated by Django 6.0.2 on 2026-02-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_message_recipient_tenant_alter_message_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningrequest',
            name='consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screeningrequest',
            name='consent_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('consented', 'Consented'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='screeningrequest',
            name='consent_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='screeningrequest',
            name='tenant_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screeningrequest',
            name='tenant_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='screeningrequest',
            name='tenant_ssn_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
