# Generated by Django 6.0.2 on 2026-02-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_screeningrequest_consent_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='listing_amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='unit',
            name='listing_available_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='listing_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='unit',
            name='listing_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='unit',
            name='listing_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='listing_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='listing_lease_term',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='unit',
            name='listing_photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='unit',
            name='listing_slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='listing_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
