# Generated by Django 6.0.2 on 2026-02-14 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_unit_is_listed_unit_listing_amenities_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_slug', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('denied', 'Denied'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('ssn_last4', models.CharField(blank=True, max_length=4)),
                ('current_address', models.CharField(max_length=255)),
                ('current_city', models.CharField(max_length=120)),
                ('current_state', models.CharField(max_length=120)),
                ('current_zip', models.CharField(max_length=20)),
                ('current_landlord_name', models.CharField(blank=True, max_length=255)),
                ('current_landlord_phone', models.CharField(blank=True, max_length=30)),
                ('current_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reason_for_moving', models.TextField(blank=True)),
                ('employer_name', models.CharField(blank=True, max_length=255)),
                ('employer_phone', models.CharField(blank=True, max_length=30)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employment_length', models.CharField(blank=True, max_length=100)),
                ('num_occupants', models.IntegerField(default=1)),
                ('has_pets', models.BooleanField(default=False)),
                ('pet_description', models.CharField(blank=True, max_length=255)),
                ('has_been_evicted', models.BooleanField(default=False)),
                ('has_criminal_history', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True)),
                ('references', models.JSONField(default=list)),
                ('consent_background_check', models.BooleanField(default=False)),
                ('consent_credit_check', models.BooleanField(default=False)),
                ('electronic_signature', models.CharField(blank=True, max_length=255)),
                ('signature_date', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_applications', to='properties.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rental_applications', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_applications', to='properties.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
