# Generated by Django 6.0.2 on 2026-02-14 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_rentalapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases', to='properties.rentalapplication'),
        ),
        migrations.AddField(
            model_name='lease',
            name='landlord_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lease',
            name='landlord_signed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='lease_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases', to='properties.document'),
        ),
        migrations.AddField(
            model_name='lease',
            name='signature_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('declined', 'Declined')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='lease',
            name='signing_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='tenant_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lease',
            name='tenant_signed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
