# Generated by Django 6.0.2 on 2026-02-14 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_transactionimport_importedtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_field', models.CharField(choices=[('description', 'Description'), ('reference', 'Reference')], default='description', max_length=20)),
                ('match_type', models.CharField(choices=[('contains', 'Contains'), ('starts_with', 'Starts With'), ('exact', 'Exact Match')], default='contains', max_length=20)),
                ('match_value', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_rules', to='properties.accountingcategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_rules', to='properties.organization')),
                ('property_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classification_rules', to='properties.property')),
            ],
            options={
                'ordering': ['-priority', 'match_value'],
            },
        ),
    ]
