# Generated by manual migration for recurring transaction expansion.
from decimal import Decimal

from django.db import migrations, models
from django.db.models.deletion import PROTECT
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0019_bankreconciliation_reconciliationmatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringtransaction",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="recurringtransaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="recurringtransaction",
            name="debit_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=PROTECT,
                related_name="recurring_debit_transactions",
                to="properties.accountingcategory",
            ),
        ),
        migrations.AddField(
            model_name="recurringtransaction",
            name="credit_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=PROTECT,
                related_name="recurring_credit_transactions",
                to="properties.accountingcategory",
            ),
        ),
        migrations.AddField(
            model_name="recurringtransaction",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="recurring_transactions",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="recurringtransaction",
            name="start_date",
            field=models.DateField(default=timezone.now),
        ),
        migrations.AddField(
            model_name="recurringtransaction",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recurringtransaction",
            name="last_run_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recurringtransaction",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("annually", "Annually"),
                    ("weekly", "Weekly"),
                ],
                max_length=20,
            ),
        ),
    ]
