# Generated by Django 6.0.2 on 2026-02-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_alter_recurringtransaction_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt', models.TextField(max_length=300)),
                ('content', models.TextField()),
                ('author_name', models.CharField(default='Onyx PM Team', max_length=100)),
                ('category', models.CharField(choices=[('product_updates', 'Product Updates'), ('property_management', 'Property Management'), ('accounting', 'Accounting'), ('ai_technology', 'AI Technology'), ('tips_tricks', 'Tips & Tricks'), ('industry_news', 'Industry News')], max_length=50)),
                ('tags', models.CharField(blank=True, default='', max_length=300)),
                ('featured_image_url', models.URLField(blank=True, default='')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_time_minutes', models.IntegerField(default=5)),
                ('meta_description', models.CharField(blank=True, default='', max_length=160)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
